### ISSUE TITLE
Minor spelling mistake:

### ISSUE THREAD

**Issue by deependujha** [roboflow/set-of-mark#1]
<img width="806" alt="Screenshot 2023-11-27 at 8 43 33 AM" src="https://github.com/roboflow/set-of-mark/assets/76887609/165420ed-f15e-4f43-956b-f2f57a08ea92">

**Comment by SkalskiP** [comment]
Will fix it today. I plan to revamp the whole README.md. And maybe create some docs page. It should be fixed today.
